### ISSUE TITLE
Use new Discord slash commands

### ISSUE THREAD

**Issue by AFCMS** [MT-CTF/ctf-discord-bot#13]

**Comment by AFCMS** [comment]
If this feature request is accepted, I can work on this

**Comment by LoneWolfHT** [comment]
I approve, thanks!

**Comment by AFCMS** [comment]
Is it ok to bump the discord.js version?

**Comment by AFCMS** [comment]
I bumped it to v13 (v12 is no longer supported)

**Comment by LoneWolfHT** [comment]
I guess so, will just have to test everything before merging

**Comment by AFCMS** [comment]
I have a working bot, but I need to setup redis server + ctf server to check if it works properly...

**Comment by LoneWolfHT** [comment]
Are you able to create a PR? It should be possible to reasonably assume the rankings connections still work

**Comment by AFCMS** [comment]
I will try to get the time this weekend
