### ISSUE TITLE
Current server information

### ISSUE THREAD

**Issue by rubenwardy** [MT-CTF/ctf-discord-bot#2]
Show currently online users, and current map

Not sure how to implement this, or if I have time to

**Comment by olliy1or** [comment]
https://github.com/MT-CTF/servermods/pull/13
https://github.com/MT-CTF/ctf-discord-bot/pull/11
these two PRs show the online players

**Comment by moreavy** [comment]
I wonder the `!cmd` command will come in the Discord Server.

**Comment by LoneWolfHT** [comment]
Done seperately
